language: python
python: "2.7"

install: pip install tox pyyaml

env:
    matrix:
        - TEST_POSIX_PROVIDER=1
        - TEST_STATIC_PROVIDER=1

before_script:
    - 'sudo $(which python) tests/scripts/create_users.py tests/data/test_users.yaml'

script: tox

after_success:
    - 'if [ $TEST_POSIX_PROVIDER ]; then pip install coveralls; else echo Skipping "pip install coveralls"; fi'
    - 'if [ $TEST_POSIX_PROVIDER ]; then coveralls; else echo Skipping "coveralls"; fi'

branches:
    only:
        - master
